/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Api } from "./Api";
import { ApiCountArgs } from "./ApiCountArgs";
import { ApiFindManyArgs } from "./ApiFindManyArgs";
import { ApiFindUniqueArgs } from "./ApiFindUniqueArgs";
import { DeleteApiArgs } from "./DeleteApiArgs";
import { ApiService } from "../api.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Api)
export class ApiResolverBase {
  constructor(
    protected readonly service: ApiService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Api",
    action: "read",
    possession: "any",
  })
  async _apisMeta(
    @graphql.Args() args: ApiCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Api])
  @nestAccessControl.UseRoles({
    resource: "Api",
    action: "read",
    possession: "any",
  })
  async apis(@graphql.Args() args: ApiFindManyArgs): Promise<Api[]> {
    return this.service.apis(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Api, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Api",
    action: "read",
    possession: "own",
  })
  async api(@graphql.Args() args: ApiFindUniqueArgs): Promise<Api | null> {
    const result = await this.service.api(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Api)
  @nestAccessControl.UseRoles({
    resource: "Api",
    action: "delete",
    possession: "any",
  })
  async deleteApi(@graphql.Args() args: DeleteApiArgs): Promise<Api | null> {
    try {
      return await this.service.deleteApi(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
