/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Catalog } from "./Catalog";
import { CatalogCountArgs } from "./CatalogCountArgs";
import { CatalogFindManyArgs } from "./CatalogFindManyArgs";
import { CatalogFindUniqueArgs } from "./CatalogFindUniqueArgs";
import { DeleteCatalogArgs } from "./DeleteCatalogArgs";
import { CatalogService } from "../catalog.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Catalog)
export class CatalogResolverBase {
  constructor(
    protected readonly service: CatalogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Catalog",
    action: "read",
    possession: "any",
  })
  async _catalogsMeta(
    @graphql.Args() args: CatalogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Catalog])
  @nestAccessControl.UseRoles({
    resource: "Catalog",
    action: "read",
    possession: "any",
  })
  async catalogs(
    @graphql.Args() args: CatalogFindManyArgs
  ): Promise<Catalog[]> {
    return this.service.catalogs(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Catalog, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Catalog",
    action: "read",
    possession: "own",
  })
  async catalog(
    @graphql.Args() args: CatalogFindUniqueArgs
  ): Promise<Catalog | null> {
    const result = await this.service.catalog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Catalog)
  @nestAccessControl.UseRoles({
    resource: "Catalog",
    action: "delete",
    possession: "any",
  })
  async deleteCatalog(
    @graphql.Args() args: DeleteCatalogArgs
  ): Promise<Catalog | null> {
    try {
      return await this.service.deleteCatalog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
