/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Service as PrismaService,
  Api as PrismaApi,
} from "@prisma/client";
import { ServiceCreateInput } from "./ServiceCreateInput";
import { Service } from "./Service";
import { ServiceFindManyArgs } from "./ServiceFindManyArgs";
import { ServiceFindUniqueArgs } from "./ServiceFindUniqueArgs";
import { ServiceWhereUniqueInput } from "./ServiceWhereUniqueInput";
import { UpdateServiceArgs } from "./UpdateServiceArgs";

export class ServiceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ServiceCountArgs, "select">): Promise<number> {
    return this.prisma.service.count(args);
  }

  async services(args: Prisma.ServiceFindManyArgs): Promise<PrismaService[]> {
    return this.prisma.service.findMany(args);
  }
  async service(
    args: Prisma.ServiceFindUniqueArgs
  ): Promise<PrismaService | null> {
    return this.prisma.service.findUnique(args);
  }
  async createService(args: Prisma.ServiceCreateArgs): Promise<PrismaService> {
    return this.prisma.service.create(args);
  }
  async updateService(args: Prisma.ServiceUpdateArgs): Promise<PrismaService> {
    return this.prisma.service.update(args);
  }
  async deleteService(args: Prisma.ServiceDeleteArgs): Promise<PrismaService> {
    return this.prisma.service.delete(args);
  }

  async findApis(
    parentId: string,
    args: Prisma.ApiFindManyArgs
  ): Promise<PrismaApi[]> {
    return this.prisma.service
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .apis(args);
  }
  async CreateNewService(args: ServiceCreateInput): Promise<Service> {
    throw new Error("Not implemented");
  }
  async GetAllServices(args: ServiceFindManyArgs): Promise<Service[]> {
    throw new Error("Not implemented");
  }
  async GetServiceById(args: ServiceFindUniqueArgs): Promise<Service> {
    throw new Error("Not implemented");
  }
  async RemoveService(args: ServiceWhereUniqueInput): Promise<Service> {
    throw new Error("Not implemented");
  }
  async UpdateExistingService(args: UpdateServiceArgs): Promise<Service> {
    throw new Error("Not implemented");
  }
}
